---
version: '3.7'
services:
    nginx:
      container_name: nginx
      image: nginx:latest
      volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
      ports:
      - target: 80
        published: 80
        protocol: tcp
      depends_on:
        - client
        - server
    client:
      image: thi6/client
      build:
        context: ./static_website
        dockerfile: Dockerfile
      ports:
      - target: 8089
        published: 8089
        protocol: tcp
    db_connector:
      image: thi6/db_connector
      build:
        context: ./db_connector
        dockerfile: Dockerfile
      depends_on:
      - mongo
      ports:
      - target: 5001
        published: 5001
    mongo:
      image: mongo
    prize_gen:
      image: thi6/prizegen:bigprize
      build:
        args:
          VERSION: bigprize
        context: ./prize_gen
        dockerfile: Dockerfile
      depends_on:
      - db_connector
      ports:
      - target: 5002
        published: 5002
    server:
      image: thi6/server
      build:
        context: ./server
        dockerfile: Dockerfile
      depends_on:
      - prize_gen
      ports:
      - target: 8084
        published: 8084
    notification_server:
      image: thi6/notification_server
      build:
        context: ./notification_server
        dockerfile: Dockerfile
      depends_on:
      - prize_gen
      ports:
      - target: 9000
        published: 9000
    text_gen:
      image: thi6/textgen:3
      build:
        args:
          VERSION: 3
        context: ./text_gen
        dockerfile: Dockerfile
      depends_on:
      - server
      ports:
      - target: 9018
        published: 9018
    num_gen:
      image: thi6/numgen:8
      build:
        args:
          VERSION: 8
        context: ./num_gen
        dockerfile: Dockerfile
      depends_on:
      - server
      ports:
      - target: 9017
        published: 9017  
...

